### ISSUE TITLE
ini file highlighting doesn't preserve highlight for strings

### ISSUE THREAD

**Issue by jjallaire** [jgm/skylighting#126] opened 2021-06-15 18:25 UTC
With pandoc 2.14.0.2 if you render the following markdown:

````markdown
```ini
[Section]
Field = "something-v4.2.4.yaml"
```
````

You get this highlighting treatment:

<img width="346" alt="image (6)" src="https://user-images.githubusercontent.com/104391/122104154-5dcf3e80-cde5-11eb-9eef-36e250a4011e.png">

Note the "2.4" highlighted as a float rather than preserving the string highlighting color.

**Comment by jgm** [comment] 2021-06-16 05:51
The problem is in the KDE ini.xml syntax definition, which seems to be very primitive.
I tried in the Kate editor and got the same bad highlighting:

<img width="236" alt="Screen Shot 2021-06-15 at 10 50 07 PM" src="https://user-images.githubusercontent.com/3044/122164777-233cc480-ce2c-11eb-8985-51330ed8b75b.png">

So, we are implementing this correctly but the underlying syntax definition needs improvement.  (If you improve it, submit upstream to KDE as described in this project's README.)

**Comment by jjallaire** [comment] 2021-06-16 09:10
Okay, we will take a shot at improving this and submit to KDE once we have. Thanks!

**Comment by jjallaire** [comment] 2021-06-16 10:06
Issue w/ proposed fix filed here: https://invent.kde.org/frameworks/syntax-highlighting/-/issues/10

**Comment by jgm** [comment] 2021-06-16 15:20
Great. Let's see if you get any reactions from KDE.  If they're okay with it, we can merge it here too.

**Comment by jgm** [comment] 2021-06-18 15:38
Thinking more about this, it seems to me that instead of adding special support for quoted strings, you should *remove* the special highlighting of numbers.  Reasons:

1. The description of ini file format here https://en.wikipedia.org/wiki/INI_file#Quoted_values says nothing at all about special treatment of numbers.
2. With the fix you've given, we'd still get similar problems with numbers in the middle of *unquoted* strings, which are allowed in ini.

**Comment by jjallaire** [comment] 2021-06-23 12:40
Okay, agreed. I re-opened the original issue w/ a new suggested patch: https://invent.kde.org/frameworks/syntax-highlighting/-/issues/10#note_262011

**Comment by jjallaire** [comment] 2021-07-14 19:52
It looks like they've merged an improved version that only colorizes numbers for values that are entirely composed of a number: https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/224

**Comment by jgm** [comment] 2021-07-16 18:21
Great, I've merged this now.

**Closed by jgm** 2021-07-16 18:21 UTC
